name: qwen-image-edit
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pip
  - pip:
    - diffusers>=0.35.0
    - transformers>=4.35.0
    - accelerate>=0.25.0
    - safetensors>=0.4.0
    - pillow>=9.0.0
    - numpy>=1.21.0
    - tqdm>=4.65.0
    - click>=8.0.0
    - rich>=13.0.0
    - pyyaml>=6.0.0
    - requests>=2.28.0
    - -e .
